DEBUG = {}

DEBUG.BOUNDING_BOXES = true
--DEBUG.DATAPACK_LOAD = true
--DEBUG.DATAPACK_CONTENTS = true
--DEBUG.REG_APPLY = true
--DEBUG.MASKS = true

--DEBUG.EVENT_SUBS = true
--DEBUG.EVENT_ATTACHES = true

--DEBUG.OVERLOAD = true

--DEBUG.INV_DETAILS = true